weights: weights/yolov5s.pt
cfg: models/yolov5s.yaml
data: data/DOTA.yaml
hyp: data/hyp.scratch.yaml
epochs: 100
batch_size: 16
img_size:
- 1024
- 1024
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
name: ''
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
workers: 8
total_batch_size: 16
world_size: 1
global_rank: -1
